### PR TITLE
Raupies refactorings

### PR DESCRIPTION
**Pull request by cleentfaar**
Supersedes #32

All credits go to @raupie

### CODE REVIEW

**Comment by cleentfaar** [comment]
@raupie Could you have a look at the changed files and let me know if there's anything missing? I probably will merge it tomorrow. Thanks again for your work!

**Comment by raupie** [comment]
Yup I can take a look tomorrow.

**Comment by raupie** [comment]
Everything looks good to me.

**Comment by raupie** [comment]
has this pull request been applied?

**Comment by thetylerhayes** [comment]
@raupie No this still hasn't been applied, and a lot of us would really love it to be! Especially for that `as_user` setting for bots! How can we help push this through?

**Comment by raupie** [comment]
Oh geez. I thought this was. I pretty much jacked my merge and we moved away from slack so I haven't been in this repo for a while. Let me know what you need me to do

**Comment by cleentfaar** [comment]
Sorry guys been away for a while, will look at this coming weekend

**Comment by thetylerhayes** [comment]
Thanks @cleentfaar! If this gets in today (I'm working on a client project, go figure ;), :cake: is on me.

**Comment by cleentfaar** [comment]
Anything for a user of one of my packages :wink:! Seeing I am 22 hours in, hope this will still be in time.

PS I'm preparing for quite a few refactorings so I can't make a new release until I have taken another look on the entire codebase. In the meantime use the `dev-master` version in composer, or stick with this specific merge using `"cleentfaar/slack": "dev-master#7e3c2d8fe153e8c71852b4b4a199d8440dfe6095"`

**Comment by thetylerhayes** [comment]
url

Tested. Works great! You really helped me from a lot of dirty hacks here, thank you @cleentfaar.

I owe you a piece of cake.

**Pull request merged**
