### PR TITLE
`team.info` request & payload.

### PR DESCRIPTION
**Pull request by n1c**
I did my best to follow how the rest of the project is structured. Let me know if I should amend anything! :pray:

### CODE REVIEW

**Comment by n1c** [comment]
Hey; any chance I could get some eyes on this? Thanks!

**Comment by thetylerhayes** [comment]
I don't consider myself well-acquainted enough with the repo yet to approve this, but big :+1: on getting this merged.

**Comment by cleentfaar** [comment]
Hey @n1c sorry for the late response. I will merge (a rebased version of) this right now as I've done with other open PRs so that I get a good picture on what to refactor before going stable. A new release will be out soon. 

Thanks for your contribution!

**Comment by cleentfaar** [comment]
see https://github.com/cleentfaar/slack/pull/52

**Comment by n1c** [comment]
Awesome; thanks!

**Pull request closed without merging**
