### PR TITLE
adding users.getPresence method

### PR DESCRIPTION
**Pull request by carsso**
More info about users.getPresence method on https://api.slack.com/methods/users.getPresence

### CODE REVIEW

**Comment by carsso** [comment]
Check are failing because of guzzle 6.0, everything works fine with 5.3.0.

**Comment by cleentfaar** [comment]
@carsso Sorry for the late reply. I will be checking guzzle compatibility asap and merge your PR after that.

**Comment by cleentfaar** [comment]
Could you rebase this PR? I've merged some other PRs today that made the ApiClient work with v6, so if you can make yours compatible with that I can merge this one too.

**Comment by carsso** [comment]
done ;)

**Comment by cleentfaar** [comment]
@carsso Awesome thanks again!

**Pull request merged**
